### ISSUE TITLE
Object detection model weights

### ISSUE THREAD

**Issue by Robotmurlock** [AtomScott/TeamTrack#2]
Hey, could you shave the YOLOv8 object detection model weights you used in the paper? Thanks in advance.

**Comment by AtomScott** [comment]
Sure, there are here:
https://github.com/AtomScott/TeamTrack/tree/main/scripts/benchmark/yolov8

**Comment by Robotmurlock** [comment]
Seems that I have missed that part of the repo. Thank you very much! :)
