### ISSUE TITLE
Does TeamTrack data provide labels for "ball"?

### ISSUE THREAD

**Issue by edwardnguyen1705** [AtomScott/TeamTrack#4]
Dear @AtomScott ,

Thanks for sharing your great work.

I have downloaded your dataset and I check that it does not provide bounding box labels for `ball`?

**Comment by AtomScott** [comment]
Thanks for the comment.
The ball should be included in the csv file, try visualizing the bounding boxes for a given frame.

**Comment by edwardnguyen1705** [comment]
> Thanks for the comment. The ball should be included in the csv file, try visualizing the bounding boxes for a given frame.

Thanks for your info. I see the ball info is at the end.
